name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install moc
      run: npx mocv use latest

    - name: install mops
      run: npm i ic-mops -g

    - name: install mops packages
      run: mops install

    - name: "install dfx"
      run: |
       mkdir /home/runner/bin
       echo "/home/runner/bin" >> $GITHUB_PATH
       DFX_INSTALL_ROOT=/home/runner/bin/ sh -ci "$(curl -sSL https://internetcomputer.org/install.sh)"
       chmod +x /home/runner/bin/dfx

    - name: "install ic-repl"
      run: |
       wget --output-document /home/runner/bin/ic-repl https://github.com/chenyan2002/ic-repl/releases/download/0.3.8/ic-repl-linux64
       chmod +x /home/runner/bin/ic-repl
    
    - name: "check"
      run: make check-strict
    
    - name: "test"
      run: make test
